# Generated by Django 6.0.2 on 2026-06-07 00:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('numero_identite', models.CharField(max_length=50, unique=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propriétaire',
                'verbose_name_plural': 'Propriétaires',
            },
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en m²', max_digits=12)),
                ('coordonnees_gps', models.CharField(help_text='Format: latitude,longitude', max_length=100)),
                ('adresse', models.TextField()),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('litige', 'En litige'), ('en_transaction', 'En transaction')], default='libre', max_length=20)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('proprietaire_actuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terrains', to='api.proprietaire')),
            ],
            options={
                'verbose_name': 'Terrain',
                'verbose_name_plural': 'Terrains',
            },
        ),
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu')], default='ouvert', max_length=10)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='litiges_declares', to='api.proprietaire')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='litiges', to='api.terrain')),
            ],
            options={
                'verbose_name': 'Litige',
                'verbose_name_plural': 'Litiges',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('signature_numerique', models.CharField(editable=False, max_length=64, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='api.proprietaire')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.terrain')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='api.proprietaire')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
