# Generated by Django 6.0.2 on 2026-06-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hash_fichier',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
