# Generated by Django 6.0.2 on 2026-06-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_document_hash_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='litige',
            name='date_resolution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='resolution',
            field=models.TextField(blank=True, default=''),
        ),
    ]
