# Generated by Django 6.0.2 on 2026-06-07 08:19

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_litige_date_resolution_litige_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='numero_identite',
            field=api.models.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='telephone',
            field=api.models.EncryptedField(),
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('statut_http', models.PositiveSmallIntegerField(default=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date'],
            },
        ),
    ]
